server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://supercodingpj2-db.c3mauekkk9cl.ap-northeast-2.rds.amazonaws.com:3306/supercodingpj2
        username: admin
        password: codingpj

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MySQL8Dialect


    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB

# Swagger
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html
    override-with-generic-response: false
    default-produces-media-type: application/json
    remove-broken-reference-definitions: true

#s3
cloud:
    aws:
        credentials:
            access-key: ${AWS_ACCESS_KEY}
            secret-key: ${AWS_SECRET_KEY}
        region:
            staticRegion: ${AWS_REGION}
        s3:

            bucket: ${AWS_BUCKET_NAME}

oauth:
    google:
        client-id: ${GOOGLE_CLIENT_ID}
        client-secret: ${GOOGLE_CLIENT_SECRET}
        redirect-uri: ${GOOGLE_REDIRECT_URI}
    kakao:
        client-id: ${KAKAO_CLIENT_ID}
        client-secret: ${KAKAO_CLIENT_SECRET}
        redirect-uri: ${KAKAO_REDIRECT_URI}
    naver:
        client-id: ${NAVER_CLIENT_ID}
        client-secret: ${NAVER_CLIENT_SECRET}
        redirect-uri: ${NAVER_REDIRECT_URI}

