name: Deploy to EC2

on:
  push:
    branches:
      - main

#jobs:
#  Deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: SSH로 EC2에 접속하기
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ${{ secrets.EC2_USERNAME }}
#          key: ${{ secrets.EC@_PRIVATE_KEY }}
#          script_stop: true
#          script: |
#            cd/home/ubuntu/app/BE
#            git pull origin main
#            ./gradlew clean build -x test
#            sudo fuser -k -n tcp 8080 || true
#            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &


jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository에 올린 파일들 불러오기
        uses: actions/checkout@v4

      - name: gradlew에 실행 권한 부여
        run: chmod +x gradlew

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name : application.yml 파일 만들기
        run : echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.yml

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build -stacktrace

      - name: 테스트 실패 상세 로그 출력 (정확한 Bean 에러 확인용)
        if: failure()
        run: cat build/reports/tests/test/classes/supercoding.pj2.Pj2ApplicationTests.html || echo "클래스 리포트 없음"

      - name: 빌드된 파일 이름 변경하기
        run: mv ./build/libs/*SNAPSOHT.jar ./project.jar

      - name: SCP로 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.jar
          target: /home/ubuntu/BE/tobe


      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/app/BE/current
            mkdir /home/ubuntu/app/BE/current
            mv /home/ubuntu/app/BE/tobe/project.jar /home/ubuntu/app/BE/current/project.jar
            cd /home/ubuntu/app/BE/current
            sudo fuser -k - n tcp 8080 || true
            nohup java -jar proejct.jar > ./output.log 2>&1 &
            rm -rf /home/ubuntu/app/BE/tobe